### ISSUE TITLE
[BUG] resolve_path does not resolve paths from directories inside virtual drivers (subst)

### ISSUE THREAD

**Issue by williamjamir** [fastapi/typer#244]
### Describe the bug

`resolve_path` doesn't resolve paths from directories inside a virtual driver created with [`subst`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/subst)

### To Reproduce

* Create a file `main.py` with:

```Python
import typer
from pathlib import Path

def app(name: Path = typer.Option(Path('.'), resolve_path=True)):
    typer.echo(f"name parameter content: {name}")
    typer.echo(f"name parameter content after 'Path.resolve()': {name.resolve()}")


if __name__ == "__main__":
    typer.run(app)
```

* Call it with informing a path that is inside a subst directory:

```bash
C:\Users\william
(.env) λ mkdir typer

C:\Users\william
(.env) λ subst t: C:\Users\william\typer

C:\Users\william
(.env) λ T:

T:\
(.env) λ python main.py

```

* It outputs:
```
name parameter content: T:\
name parameter content after 'Path.resolve()': C:\Users\william\typer
```

* But I expected it to output:

```
name parameter content: C:\Users\william\typer
name parameter content after 'Path.resolve()': C:\Users\william\typer
```

### Expected behavior

I was expecting that the `name` parameter to be the result of `Path.resolve()`

### Environment

* OS: Windows
* Typer Version: 0.3.2
* Python version: Python 3.6.13

**Comment by daddycocoaman** [comment]
This isn't a Typer bug. That is how Path.resolve() works. It resolves symlinks are other sort of "virtual" path oddities. Here is an example:

![image](https://user-images.githubusercontent.com/21189155/110273869-88fef200-7f9b-11eb-98a8-8f22ba1ac545.png)

**Comment by daddycocoaman** [comment]
This isn't a Typer bug. Underneath, Typer creates Click objects, and in this case creates click.Path. When `resolve_path` is set, Click will resolve the path uses `os.path.realpath` to resolve things. 

However, resolving symbolic links with this on Windows wasn't possible until Python 3.8. In other words, the behavior of `os.path.realpath` is different between Python 3.7 and 3.8. Since you're using 3.6, you aren't getting the correct value!

https://docs.python.org/3/library/os.path.html#os.path.realpath

**Comment by davidism** [comment]
Click will be reverting the change in 8.0.2, as it was causing other issues. I'd suggest upgrading Python to get newer Python behavior in this case. Or if you want to dig into it further, I'm open to another try at the change in 8.0.3 or 8.1.0 depending on timing/impact.
