### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by wizard-28** [fastapi/typer#371]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Typer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Typer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Typer but to [Click](https://github.com/pallets/click).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
from __future__ import annotations

import typer

app = typer.Typer()


def main():
    app()


@app.command()
def test(flag: bool | None = typer.Option(None, "--flag", "-f", help="A flag")):
    print(flag)


if __name__ == "__main__":
    main()
```

### Description

1. Run the example code
2. See the error: https://sourceb.in/SxyHEeLZxf

### Operating System

Linux

### Typer Version

0.4.0

### Python Version

Python 3.8.10

**Comment by ankitpv** [comment]
`|` was added in python 3.10, so not available in python 3.8.
```py
def test(flag: bool | None = typer.Option(None, "--flag", "-f", help="A flag")):
```
Either you can use `typing.Union` or you can use string for type annotation, like:
```py
def test(flag: "bool | None" = typer.Option(None, "--flag", "-f", help="A flag")):
```

**Comment by wizard-28** [comment]
> `|` was added in python 3.10, so not available in python 3.8.
> 
> ```python
> def test(flag: bool | None = typer.Option(None, "--flag", "-f", help="A flag")):
> ```
> 
> Either you can use `typing.Union` or you can use string for type annotation, like:
> 
> ```python
> def test(flag: "bool | None" = typer.Option(None, "--flag", "-f", help="A flag")):
> ```

---

> `from __future__ import annotations`

I've imported it from `__future__` though.

Also, this sample code works in python 3.8, as I've imported `annotations`

```py
from __future__ import annotations


def test(arg: int | str) -> None:
    print(arg)


test("string")
test(999)
```

![](https://0x0.st/oNOr.png)

**Comment by astrochun** [comment]
I'm getting the same issue with python 3.10:
```
RuntimeError: Type not yet supported: str | None
```

**Comment by jrmidkiff** [comment]
```
def create(self, 
        major: int|str, minor: int|str, patch: int|str, 
        prerelease: str, buildmetadata: str) -> 'Version': 
    pass
```
This causes `TypeError: unsupported operand type(s) for |: 'type' and 'type'` when I import this file into ipython, but not when I run this file from the command line or start a python session from the command line and import the file that way. 
Python version 3.10.4

**Comment by parallaxe** [comment]
Would the typealias

String = str | None
be a possibility? It should match the semantics. The other types (Float, ...) could also be turned into aliases.

Though, Typealias seems to require python 3.10 (https://peps.python.org/pep-0613/).
Requiring 3.10 would be no issue for me as I'm already developing with it.

Is supporting < 3.10 a hard requirement for this module?

**Comment by johnthagen** [comment]
Duplicate of

- #348

**Comment by svlandeg** [comment]
Confirmed that either #676 or #548 will fix this issue!

**Comment by svlandeg** [comment]
Confirmed that either #676 or #548 will fix this issue!

**Comment by Asthestarsfalll** [comment]
> Confirmed that either #676 or #548 will fix this issue!

Hi, When will those PRs merge?

**Comment by svlandeg** [comment]
> > Confirmed that either #676 or #548 will fix this issue!
> 
> Hi, When will those PRs merge?

When Tiangolo has a chance to review them - he's aware of them, but has many other things to do as well 😉

**Comment by alanwilter** [comment]
Oh, I need this fix please!

**Comment by blackpearl1022** [comment]
`def to_numpy(x: torch.Tensor | np.ndarray | dict | list) -> np.ndarray:
TypeError: unsupported operand type(s) for |: 'torch._C._TensorMeta' and 'type'`

How to do in this case ?
