### ISSUE TITLE
How to disable bool option counterpart?

### ISSUE THREAD

**Issue by sidekick-eimantas** [fastapi/typer#467]
### First Check

- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Typer documentation, with the integrated search.
- [X] I already searched in Google "How to X in Typer" and didn't find any information.
- [X] I already read and followed all the tutorial in the docs and didn't find an answer.
- [X] I already checked if it is not related to Typer but to [Click](https://github.com/pallets/click).

### Commit to Help

- [X] I commit to help with one of those options 👆

### Example Code

```python
@app.command()
def install(packages: list[str], list_available: bool = typer.Option(default=False, help="List available packages and exit.", show_default=False)) -> None:
    print(packages)
```

### Description

The above code creates a counterpart, --no-list-available:
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/111279287/195053813-cb5ada99-0c9d-4688-8170-3e94b0103b01.png">

Is there any way to turn the counterparts off?

### Operating System

macOS

### Typer Version

0.6.1

### Python Version

Python 3.10.7

**Comment by texasfight** [comment]
Docs are here: https://typer.tiangolo.com/tutorial/parameter-types/bool/

You need to put "--list-available" as your second arg. I think the kwarg for it is `param_decls`

**Comment by tiangolo** [comment]
Thanks for the help here @texasfight  ! 👏  🙇 

Thanks for reporting back and closing the issue @sidekick-eimantas  👍
